### ISSUE TITLE
Open brace character is not escaped correctly.

### ISSUE THREAD

**Issue by chr15m** [falstro/ghost-text-vim#15]
To replicate:

 * Start `./ghost-text-server.tcl`.
 * Open new GitHub issue.
 * Click in issue body text area.
 * Click on GhostText icon to connect.
 * Type a bunch of text and include an open brace charater: `{`
 * Observe updates do not get propagated correctly when an open brace is present.

**Comment by chr15m** [comment]
Some more detail. When I use the debugging output from #14 I get the following:

For text `test one two` in the editor:
`Sending: 23 {"text":"test one two"}`

Inserting a single brace `{` character to make `test { one two`:
`Sending: 31 \"text\":\"test\ \{\ one\ two\"`

Something about the single brace causes it to escape the whole string and leave off the real braces. If I add a closing brace it goes back to behaving correctly:

`Sending: 32 {"text":"test { one two } yeah"}`

**Comment by falstro** [comment]
Thanks, fixed - I don't know why I tried to be clever and have the list command generate the
braces.
