### ISSUE TITLE
Doesn't work when started via crontab

### ISSUE THREAD

**Issue by peey** [falstro/ghost-text-vim#16]
I'm facing a weird issue. I added 
```
@reboot /path/to/dir/containing/ghost-text-server.tcl
```
and I can confirm that the job is started (I tried starting it again via command line, but got the error `couldn't open socket: address already in use`, then I check via `ps aux | grep ghost-text-server.tcl$` that indeed the script is running)

But it doesn't open up GVim. If I run it on terminal then it works fine.

**Comment by falstro** [comment]
If you simply start it from a crontab it can't connect to the X server. It
must be started in a way that the DISPLAY-variable is set correctly, and
that it has access to your X cookie. If it's running as your user, a simple
"DISPLAY=:0 /path/to/script.tcl" should probably do the trick.

**Comment by peey** [comment]
This worked, thanks!

(Appropriately enough, this was typed on Vim via GhostText, with the script started from crontab)
