### ISSUE TITLE
Unable to find package sha1

### ISSUE THREAD

**Issue by tgrosinger** [falstro/ghost-text-vim#2]
I am attempting to run your script, but am not very familiar with TCL and can't find any information about installing the sha1 package. Here is the error I am getting:

```
$ echo 'puts $tcl_version;exit 0' | tclsh
8.6

$ tclsh ghost-text-server.tcl
can't find package sha1
    while executing
"package require sha1"
    (file "ghost-text-server.tcl" line 3)
```

Please let me know if I am going about this incorrectly, or if you have any instructions that would help me get started. Thank you.

**Comment by trapier** [comment]
This symptom went away on Fedora after installing the package named `tcllib`.

**Comment by finelli** [comment]
the same on Debian (Jessie)

**Comment by falstro** [comment]
Yup, it requires sha1, json, and json::write. These are available in the package tcllib under Debian and Ubuntu. Sha1 is required to do WebSockets, and json/json::write to properly (un-)escape the JSON being sent to and received from the browser plugin
