### ISSUE TITLE
Diacritic Support

### ISSUE THREAD

**Issue by caonUlisses** [falstro/ghost-text-vim#4]
Everytime I write down any specialchar, like à or á the connection is lost. Not a problem for English, although.

**Comment by falstro** [comment]
I've tried a couple of times to get to the bottom of this but for some reason it all ends up with me getting pure garbage (literally random bytes) from the browser plugin. Sorry about that. Did you by any chance test it with sublime or a different editor?

**Comment by caonUlisses** [comment]
I didn't. Will try later and see if I can help somehow. But probably the cause is related to the browser plugin. Awesome extension, by the way!

**Comment by pmorch** [comment]
At least I can confirm that this is a problem. Abandoning the use of this server since UTF-8 is a must for me.

**Comment by falstro** [comment]
Upps, the commit message closed the issue. Please have a try and see if it works.

**Comment by pmorch** [comment]
I can confirm that it works now.
