### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by einhander** [falstro/ghost-text-vim#8]
Is utf-8 system codepage supported?
English character printed OK. But then I switch language (russian), I see another characters instead of that I pressed.
I use vim as text editor.

**Comment by falstro** [comment]
It's actually UTF-8 by default - and I've tried a couple of times to get to the bottom of this, but from what I can tell the browser plugin doesn't handle it very well. I'm not 100% sure though, if you have sublime and could try if that works with your browser plugin, I'd be interested to know.

**Comment by falstro** [comment]
Incidentally, this is the same issue as #4. Is there a way to merge issues in GitHub?
